### ISSUE TITLE
Overflow issue for project names

### ISSUE THREAD

**Issue by emilyhorsman** [emilyhorsman/codeofconductlink#19]
![screen shot 2015-06-28 at 7 38 13 pm](https://cloud.githubusercontent.com/assets/3536823/8398858/74a8a98a-1dcd-11e5-8fd1-4f864d0a25d1.png)

What does everyone think the best way to handle this is? Truncate it? Wrap it (can someone do the styling for this?)?

**Comment by simonv3** [comment]
How about truncating combined with wrapping & position:absolute on hover? I haven't tried this before, so no idea if it's possible / aesthetically smart.

**Comment by hawkrives** [comment]
What about

``` css
.card-title {
  word-wrap: break-word;
}
```

That would break the title apart when it gets too wide…

Alternately, `text-overflow: ellipsis;` is a thing, I think?
